# Generated by Django 4.2.5 on 2023-09-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_accessmodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc', to='app.productmodel'),
        ),
        migrations.AlterField(
            model_name='accessmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc', to='app.usermodel'),
        ),
        migrations.RemoveField(
            model_name='lessonmodel',
            name='product',
        ),
        migrations.CreateModel(
            name='ProductLessonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plm', to='app.lessonmodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plm', to='app.productmodel')),
            ],
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='product',
            field=models.ManyToManyField(through='app.ProductLessonModel', to='app.productmodel'),
        ),
    ]
