# Generated by Django 4.2.5 on 2023-09-23 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_accessmodel_product_alter_accessmodel_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='lessonmodel',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductLessonModel',
        ),
        migrations.AddField(
            model_name='lessonproductmodel',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plm', to='app.lessonmodel'),
        ),
        migrations.AddField(
            model_name='lessonproductmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plm', to='app.productmodel'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='lessons',
            field=models.ManyToManyField(through='app.LessonProductModel', to='app.lessonmodel'),
        ),
    ]
