# Generated by Django 4.2.5 on 2023-09-23 17:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lessonproductmodel_remove_lessonmodel_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewsmodel',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='lessons',
            field=models.ManyToManyField(related_name='products', through='app.LessonProductModel', to='app.lessonmodel'),
        ),
        migrations.AlterField(
            model_name='viewsmodel',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vws', to='app.lessonmodel'),
        ),
        migrations.AlterField(
            model_name='viewsmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vws', to='app.usermodel'),
        ),
    ]
